# Generated by Django 6.0 on 2025-12-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediflow', '0003_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
