# Generated by Django 6.0 on 2025-12-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediflow', '0006_user_groups_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngoprofile',
            name='ngo_type',
        ),
    ]
