# Generated by Django 6.0 on 2025-12-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediflow', '0007_remove_ngoprofile_ngo_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='ngoprofile',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ngoprofile',
            name='contact_person',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngoprofile',
            name='ngo_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ngoprofile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ngoprofile',
            name='registration_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('donor', 'Donor'), ('ngo', 'NGO'), ('admin', 'Admin')], default='donor', max_length=20),
        ),
    ]
