# Generated by Django 6.0 on 2025-12-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediflow', '0010_medicine_ngorequest_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
