# Generated by Django 6.0 on 2025-12-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediflow', '0011_medicine_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Drops', 'Drops'), ('Ointment', 'Ointment'), ('Other', 'Other')], default='Tablet', max_length=50),
        ),
    ]
